name: Custom Action Workflow

on: workflow_dispatch

jobs:
    action-build:
        runs-on: ubuntu-latest
        steps:
            - name: Action Checkout
              uses: actions/checkout@v6

            - name: Use Composite Action
              id: greet-step
              uses: ./.github/actions/setup-and-greet
              with:
                name: Hina
                language: Spanish

            - name: Print Greet value
              run: echo "Greet variable value is ${{ steps.greet-step.outputs.greeted }}"