name: Github Artifacts

on: workflow_dispatch

jobs:
    upload-artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Generate a log file
              run: echo "Test run completed at $(date)" > report.log

            - uses: actions/upload-artifact@v6
              with:
                name: my-artifact
                path: report.log
    

    download-artifacts:
        runs-on: ubuntu-latest
        needs: upload-artifacts
        steps:
            - uses: actions/download-artifact@v6
              with:
                  name: my-artifact
                  # path: ./downloads

            - name: Print The file contents
              # run: cat ./downloads/report.log
              run: cat report.log
