name: Conditional Basics

on: push

jobs: 
    testing:
        if: github.event_name == 'push'
        runs-on: self-hosted
        steps:
            - name: Runs on main Branch
              id: step_id
              if: github.ref == 'refs/heads/main'
              run: echo "Run Condition if is Satisfied"
              continue-on-error: true

            - name: Step Failer
              if: steps.step_id.outcome == 'success'
              run: echo "Previous Step succeded and this step got executed"

            - name: Force Fail
              run: exit 1
              # continue-on-error: true

            - name : Print Statement
              run: echo "Continue the flow because of the above continue error"
            