name: github-hosted-runners

on: push

jobs:
    github-runners:
        strategy:
            matrix:
                os-version: ["ubuntu-latest", "windows-latest", "macos-latest"]
        runs-on: ${{ matrix.os-version }}
        steps:
            - name: OS name
              run: lsb_release -a
            - name: Print Hostname
              run: hostname
            - name: Print USER
              run: echo $USER

