name: github-hosted-runners

on: push

jobs:
    github-runners:
        strategy:
            matrix:
                os-version: ["ubuntu-latest", "windows-latest", "macos-latest"]
        runs-on: ${{ matrix.os-version }}
        steps:
            - name: Print Version Info
              if: matrix.os-version == 'ubuntu-latest'
              run: | 
                python version
                docker version
                git version
                node version


            - name: Print Windows Info
              if: matrix.os-version == 'windows-latest'
              run: |
                systeminfo | findstr /B /C:"OS Name"
                hostname
                whoami

            - name: Print MacOS Info
              if: matrix.os-version == 'macos-latest'
              run: |
                sw_vers -productName
                hostname
                whoami