name: Github Secrets

on: workflow_dispatch

jobs:
    secrets:
        runs-on: ubuntu-latest
        env:
            MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }} 
        steps:
            - name: Check Out Code
              uses: actions/checkout@v5

            - name: Read the Secret Message
              if: env.MY_SECRET_MESSAGE != ''
              run: echo "The secret is set - True"

            - name: Print the Var Directly
              run: echo ${{ secrets.MY_SECRET_MESSAGE }}

            - name: Print the ENV VAR
              run: echo "$MY_SECRET_MESSAGE"