name: Github Secrets

on: workflow_dispatch

jobs:
    secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@v5

            - name: Read the Secret Message
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }} 
              if: env.MY_SECRET_MESSAGE != ''
              run: echo "The secret is set - true"
