# This is workflow name
name: Hello

# workflow runs on a trigger
on:
  push:
    branches: [main]
      
jobs:
    greet: # This is Job name
        runs-on: ubuntu-latest # Job will run on this server given by Github for free
        steps:
            - name: action/checkout
              uses: actions/checkout@v4
            - name: Actions Greeting
              run: echo "Hello from GitHub Actions!"
            - name: Printing Info
              run: | 
                date
                ls 
                lsb_release -a
                ${{ github.ref_name }}
