# This is workflow name
name: Hello Cron

# workflow runs on a trigger
on: 
  workflow_dispatch:
  # schedule:
  #     - cron: '30 2 * * *'   
      
jobs:
    greet: # This is Job name
        runs-on: ubuntu-latest # Job will run on this server given by Github for free
        steps:
            - name: action/checkout
              uses: actions/checkout@v6
            - name: Actions Greeting
              run: echo "Hello from GitHub Actions!"
            - name: Printing Info
              run: | 
                date
                ls 
                lsb_release -a
                echo ${{ github.ref_name }}
