name: pr-check

on:
    pull_request:
        branches: [main]

jobs:
    checking-trigger: 
       runs-on: ubuntu:latest
       steps:
        - name: Print Branch
          run: echo "PR check running for branch ${{ github.head_ref }}"
        - name: Print Branch again
          run: echo "PR check running for branch again ${{ github.head_ref }}"
        - name: Print Branch for the thord time
          run: echo "PR check running for branch 3rd time again ${{ github.head_ref }}"
          