name: pr-check

on:
    pull_request:
        branches: [main]

jobs:
    checking-trigger: 
       runs-on: ubuntu-latest
       steps:
        - name: Test Rerun
          run: echo "Testing after runs-on fix on branch ${{ github.head_ref }}"
      