name: Reusable Build

on:
    workflow_call:
        inputs:
            app-name:
                type: string
                required: true
            environment:
                type: string
                required: true
                default: staging
        secrets:
            docker_token:
                required: true
        outputs:
            build_ver:
                description: "The Version Variable output"
                value: ${{ jobs.set_outputs.outputs.version }}
        

jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Prints Building <app_name> for <environment>
              run: echo "Building ${{ inputs.app-name}} for ${{ inputs.environment}}"

            - name: Prints Docker Token
              run: echo "Docker token is set - ${{ secrets.docker_token }}"

    
    set_outputs:
        runs-on: ubuntu-latest
        outputs: 
            version: ${{ steps.ver-id.outputs.ver }}
        steps:
            - name: Build Version
              id: ver-id
              run: |
                sha=${GITHUB_SHA:0:7}
                echo "ver=v1.0@$sha" >> "$GITHUB_OUTPUT"
