name: Smart Pipeline

on: 
    push:
        branches: [dev]

jobs:
    lint:
        runs-on: ubuntu-latest
        
    test:
        runs-on: ubuntu-latest
    
    summary:
        needs: 
            - lint
            - test
            # needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Print Push Branch
              run: echo "${{ github.ref_name }}" # Context style (Expression)
              # run: echo "$GITHUb_HEAD_REF" --> # Env variable direct use

            - name: Print Commit Message
              run: echo "${{ github.event.head_commit.message }}"
