name: URL Status Checker Workflow

on: workflow_dispatch

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout new repo
              uses: actions/checkout@v6

            - name: Setup Python
              uses: action/setup-python@v6
              with:
                python-version: 3.14

            - name: Run the Python Script
              run: python \.github\status_checker.py