name: Tests Workflow

on: push

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Run Basic Linux Comamnds
              run: |
                hostname
                htop
                free -h